on:
  push:
    branches:
      - main
jobs: 
  snyk:
    runs-on: ubuntu-latest
    env:
      ACTION: Snyk job
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: clarkio/snyk-cli-action@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Send telegram notification if failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }} 
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *Repository*: ${{ github.repository }}

            *Action*: ${{ env.ACTION }}
            *Status*: ${{ job.status }}
            *Author*: ${{ github.actor }}

            *Commit message*: ${{ github.event.commits[0].message }}
            *Link*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          format: "markdown"
          disable_web_page_preview: true
